config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('school/', include('school.urls', namespace='school')),

    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, activate, RestoreView, main, UserViewSet

app_name = UsersConfig.name


urlpatterns = [
    path('main', main, name='main'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email_verify/', TemplateView.as_view(template_name='users/verify.html'), name='email_verify'),
    path('activate/<token>', activate, name='activate'),
    path('restore/', RestoreView.as_view(), name='restore'),
]

router = routers.SimpleRouter()
router.register('user', UserViewSet)

urlpatterns += router.urls

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    city = models.CharField(max_length=100, verbose_name='город', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    token = models.CharField(max_length=100, default='not_token', verbose_name='token')
    email_verify = models.BooleanField(default=False, verbose_name='верификация почты')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            fild.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()
        for field_name, fild in self.fields.items():
            fild.widget.attrs['class'] = 'form-control'

users/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView
from rest_framework.viewsets import ModelViewSet

import users
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from users.serializer import UserSerializer
from users.utils import create_token


def main(request):
    context = {
    }
    return render(request, 'users/main.html', context)


class UserViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:email_verify')

    def form_valid(self, form):
        new_user = form.save()
        new_user.token = create_token()
        send_mail(
            subject='Подтвердите почту',
            message=f'Пройдите по ссылке http://127.0.0.1:8000/users/activate/{new_user.token}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


def activate(request, token):
    user = User.objects.get(token=token)
    user.email_verify = True
    user.save()
    return render(request, 'users/activate.html')


class RestoreView(TemplateView):
    template_name = 'users/restore.html'

    def post(self, **kwargs):
        context = self.get_context_data(**kwargs)
        email = self.request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except users.models.User.DoesNotExist:
            context['description'] = 'Неверный email. Попробуйте еще раз'
        else:
            new_pas = create_token()
            user.set_password(new_pas)
            user.save()

            send_mail(
                    subject='Восстановление пароля',
                    message=f'Ваш новый пароль {new_pas}',
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[email]
                )
            return redirect(reverse('users:login'))
        return self.render_to_response(context)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/activate.html
{% extends 'users/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title" align="center">Активация прошла успешно</h3>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=5">
    <title>Интернет обучение</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Интернет обучение</h5>
    {% include 'users/includes/inc_menu.html' %}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <p align="center">
                Интернет обучение
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </p>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Вход
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
            </div>
            <div>
                <a href="{% url 'users:restore' %}">Восстановить пароль</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/main.html
{% extends 'users/base.html' %}

{% block content %}

    <div class="col-12">
        <div class="card" align="center">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><h5>1: </h5></li>
                <li class="list-group-item"><h5>2: </h5></li>
                <li class="list-group-item"><h5>3: </h5></li>
            </ul>
        </div>
        <div class="row" align="center">

        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Регистрация</button>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/restore.html
{% extends 'users/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Восстановление пароля
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                Введите свой email
                <div>
                    <label for="email"></label>
                    <input type="text" name="email" class="form-control" id="email" placeholder="email">
                </div>

                <div class="card-footer" align="center">
                    <button type="submit" class="btn btn-success">Восстановить</button>
                </div>
            </div>

            <div class="card-footer"></div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'users/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Профиль
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/verify.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Подтверждение почты</title>
</head>
<body>
    <div class="col-6">
        <div class="col-3">
            <h3 align="center">Перейдите в свою почту и пройдите по ссылке для подтверждения</h3>
        </div>
    </div>
</body>
</html>